### ISSUE TITLE
Problem with Question 5 and question 6 explanation

### ISSUE THREAD

**Issue by sechlerm** [MOLB7621/problem-set-1#11]
Okay I know these are extremely simple questions and I'm just missing it so I apologize and thank you in advance!
For some reason I cannot get the word count for the hamlet problem to work- question 5. While the expected answer is 57 I keep getting an output of 50. I'm using this line 
grep 'bloody' $datasets/hamlet.txt | wc -w

When I count by hand the lines that get pulled from the grep, I count 50 words so I'm not sure what 7 words the grep is missing?

Also on number 6 I was hoping to understand better why the tr -d '\n' line is required to get a correct count. I understand that the tr is translating it to a standard output for the character count (right?) but I'm confused why the new line deletion is necessary in the first place- is that something that's just safe to put into all code like this or is there a specific reason it was needed this time?

**Comment by jayhesselberth** [comment]
- There are a few instances of "bloody" that are capitalized. You can do case-insensitive matching with `grep -i`.

- Unfortunately `wc` will count invisible characters (e.g., `\n`, `\t`). In this case there is a `\n` at the end of the sequence that specifies the end of the line. The `tr -d '\n'` command says "delete new line characters' and the output of that command is piped to `wc`.

**Comment by jayhesselberth** [comment]
Also see #1
