### ISSUE TITLE
Travis added to problem set

### ISSUE THREAD

**Issue by jayhesselberth** [MOLB7621/problem-set-1#4]
Travis should now be working for problem set 1.

You will need to pull the travis content into your forked repository:

```
$ git remote add upstream http://github.com/MOLB7621/problem-set-1
$ git fetch upstream
$ git checkout master
$ git rebase upstream/master
```

Then you need to convert your fork from a private repo to a public one. See the "Settings" tab at the top.

Then go to https://travis-ci.org/MOLB7621/problem-set-1.

If you don't see your own build, you need to first add the repository (plus sign next to "My Reposiories" on the left). After you add the repo, change "MOL7621" in the URL to your github username, and the page should contain the output of tests after your commit / push actions.

Please confirm if you get this to work (or not).

cc @MOLB7621/students @MOLB7621/tas

**Comment by lkwhite** [comment]
Working for me, in the sense that Travis is seeing my incomplete/failing build now. 

Stuff I worked out while troubleshooting: Make sure to have the new public repository forked and that it's named correctly first (see https://github.com/MOLB7621/problem-set-1/issues/5).  If you don't see your build, go to add the repo per the instructions above, and the repo is _also_ missing, hit the button next to your name to sync Travis with your GitHub account and it should pop up.

**Basic hw workflow if I'm grokking how GitHub/Travis play together here is then:**
Fork the original MOLB problem set repo, clone it to your local workspace, create one (or more) files in that repo in the process of working on the homework, git add (to add newly-created files to the list of stuff Git's tracking), git commit (to commit the changes to Git), push the whole thing back up to your forked master (git push https://github.com/$USERNAME_HERE/problem-set-1.git), then load the Travis page above to see if your committed build passes. Iterate working/adding any new files/committing changes/pushing commits/reloading Travis as necessary.
