### ISSUE TITLE
Forked Problem-set-1 Now "private" for some reason

### ISSUE THREAD

**Issue by llangholz89** [MOLB7621/problem-set-1#5]
So my forked Problem-set-1 repo now says Private next to it, so when I go to access it on GitHub is says that the repository is disabled.  I tried to refork the Problem-set-1 repo from the MOLB account, which worked but the title now says Problem-set-2.  It has the right files within, the name is just off for some reason.  Is there any way to change this name to avoid any confusion? Also, is there any way to delete the old Problem-set-1 repo?? 

Thanks for the help; still trying to get used to GitHub...

-Logan

**Comment by jayhesselberth** [comment]
It looks like [this](https://help.github.com/articles/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility/#changing-a-private-repository-to-a-public-repository) is the issue.

To address this in the future I would get a free educate account (see reference above). It may be that once that is activated you will be able to delete the forked repo. 

I have now idea why it would say problem-set-2 though.

Can you go into the repo and post the output of:

```
$ cat .git/config
```

**Comment by gkirk07** [comment]
I ran into the same issue as Logan, is this the output you want to see?

![screen shot 2016-02-06 at 1 57 15 pm](https://cloud.githubusercontent.com/assets/16768476/12869346/9c747064-ccd9-11e5-9803-c0f191eccb3b.png)

**Comment by lkwhite** [comment]
Same thing happened to me, here's my quick & dirty GitHub fix:

1. **IMPORTANT, DO NOT PASS GO, DO NOT LET GITHUB EAT YOUR HOMEWORK**: Move whatever work you've done on the homework to someplace _outside_ of your local copy of the repo. 
2. Go into your Github account, click on the prob-set-1 repo, go to the Settings tab
3. Scroll down to the red section labeled **Danger Zone**, hit Delete This Repository, follow the instructions
4. Do the same thing for prob-set-2
5. Fork the new public prob-set-1 repo; it should now have the right name
6. Clone the repo to put it back into your local workspace by copying the URL for your fork and entering  **git clone https://github.com/$your_github_username_here/problem-set-1.git** into the command line
7. Move your homework script back into that repository & carry on
